version: '3.8'

name: gatoride

services:
  api:
    container_name: api

    ports:
      - "3000:3000"

    build: 
      context: /api
      dockerfile: Dockerfile

    volumes:
      - ./api/app:/api/app

  web:
    container_name: web

    ports:
      - "5000:3000"
      - "49153:49153"

    build:
      context: /web
      dockerfile: Dockerfile

    volumes:
      - ./web/src:/web/src
      - ./web/public:/web/public
      - /web/node_modules
      - /web/.next   

  img_server:
    container_name: img_server

    ports:
      - "4000:4000"

    build:
      context: /img_server
      dockerfile: Dockerfile

    volumes:
      - ./img_server/static:/img_server/static
      - ./img_server/app:/img_server/app
    