from .models import db, Car, build_instance

# creates 100 dummy cars 
def testing_data_cars():
    cars = [
        {'make': 'Toyota', 'model': 'Corolla', 'type': 'Sedan', 'location': 'A', 'mileage': "5000", 'day': "50", 'mile': "0.25", 'status': 'available'},
        {'make': 'Ford', 'model': 'F-150', 'type': 'Truck', 'location': 'B', 'mileage': "8000", 'day': "70", 'mile': "0.35", 'status': 'repair'},
        {'make': 'Honda', 'model': 'Civic', 'type': 'Sedan', 'location': 'A', 'mileage': "6000", 'day': "45", 'mile': "0.20", 'status': 'unavailable'},
        {'make': 'Tesla', 'model': 'Model S', 'type': 'Electric', 'location': 'C', 'mileage': "2000", 'day': "150", 'mile': "0.50", 'status': 'available'},
        {'make': 'Chevrolet', 'model': 'Impala', 'type': 'Sedan', 'location': 'A', 'mileage': "7000", 'day': "55", 'mile': "0.30", 'status': 'available'},
        {'make': 'Nissan', 'model': 'Altima', 'type': 'Sedan', 'location': 'B', 'mileage': "5500", 'day': "48", 'mile': "0.22", 'status': 'unavailable'},
        {'make': 'Volkswagen', 'model': 'Jetta', 'type': 'Sedan', 'location': 'C', 'mileage': "6500", 'day': "52", 'mile': "0.28", 'status': 'unavailable'},
        {'make': 'Subaru', 'model': 'Outback', 'type': 'SUV', 'location': 'A', 'mileage': "7500", 'day': "60", 'mile': "0.32", 'status': 'available'},
        {'make': 'BMW', 'model': '3 Series', 'type': 'Sedan', 'location': 'B', 'mileage': "4000", 'day': "130", 'mile': "0.45", 'status': 'available'},
        {'make': 'Mercedes-Benz', 'model': 'C-Class', 'type': 'Sedan', 'location': 'C', 'mileage': "3000", 'day': "140", 'mile': "0.48", 'status': 'unavailable'},
        {'make': 'Hyundai', 'model': 'Elantra', 'type': 'Sedan', 'location': 'A', 'mileage': "8500", 'day': "40", 'mile': "0.18", 'status': 'available'},
        {'make': 'Audi', 'model': 'A4', 'type': 'Sedan', 'location': 'B', 'mileage': "5000", 'day': "125", 'mile': "0.42", 'status': 'unavailable'},
        {'make': 'Kia', 'model': 'Optima', 'type': 'Sedan', 'location': 'C', 'mileage': "6000", 'day': "42", 'mile': "0.20", 'status': 'available'},
        {'make': 'Mazda', 'model': 'Mazda3', 'type': 'Sedan', 'location': 'A', 'mileage': "7000", 'day': "47", 'mile': "0.21", 'status': 'unavailable'},
        {'make': 'Lexus', 'model': 'ES', 'type': 'Sedan', 'location': 'B', 'mileage': "3500", 'day': "135", 'mile': "0.47", 'status': 'available'},
        {'make': 'Chrysler', 'model': '300', 'type': 'Sedan', 'location': 'C', 'mileage': "5000", 'day': "50", 'mile': "0.25", 'status': 'unavailable'},
        {'make': 'Volvo', 'model': 'S60', 'type': 'Sedan', 'location': 'A', 'mileage': "4000", 'day': "120", 'mile': "0.40", 'status': 'available'},
        {'make': 'Buick', 'model': 'Regal', 'type': 'Sedan', 'location': 'B', 'mileage': "4500", 'day': "55", 'mile': "0.29", 'status': 'available'},
        {'make': 'Infiniti', 'model': 'Q50', 'type': 'Sedan', 'location': 'C', 'mileage': "5000", 'day': "130", 'mile': "0.46", 'status': 'unavailable'},
        {'make': 'Cadillac', 'model': 'CTS', 'type': 'Sedan', 'location': 'A', 'mileage': "3800", 'day': "140", 'mile': "0.49", 'status': 'available'},
        {'make': 'Acura', 'model': 'TLX', 'type': 'Sedan', 'location': 'B', 'mileage': "4800", 'day': "125", 'mile': "0.41", 'status': 'unavailable'},
        {'make': 'Lincoln', 'model': 'MKZ', 'type': 'Sedan', 'location': 'C', 'mileage': "5200", 'day': "60", 'mile': "0.33", 'status': 'available'},
        {'make': 'Ford', 'model': 'Mustang', 'type': 'Coupe', 'location': 'A', 'mileage': "3000", 'day': "40", 'mile': "0.20", 'status': 'available'},
        {'make': 'Toyota', 'model': 'RAV4', 'type': 'SUV', 'location': 'B', 'mileage': "4000", 'day': "45", 'mile': "0.22", 'status': 'unavailable'},
        {'make': 'Chevrolet', 'model': 'Silverado', 'type': 'Truck', 'location': 'C', 'mileage': "5000", 'day': "50", 'mile': "0.25", 'status': 'available'},
        {'make': 'Honda', 'model': 'CR-V', 'type': 'SUV', 'location': 'A', 'mileage': "5500", 'day': "55", 'mile': "0.27", 'status': 'unavailable'},
        {'make': 'Jeep', 'model': 'Wrangler', 'type': 'SUV', 'location': 'B', 'mileage': "6000", 'day': "60", 'mile': "0.28", 'status': 'available'},
        {'make': 'Nissan', 'model': 'Rogue', 'type': 'SUV', 'location': 'C', 'mileage': "6500", 'day': "65", 'mile': "0.29", 'status': 'unavailable'},
        {'make': 'Tesla', 'model': 'Model 3', 'type': 'Electric', 'location': 'A', 'mileage': "7000", 'day': "70", 'mile': "0.30", 'status': 'available'},
        {'make': 'Subaru', 'model': 'Forester', 'type': 'SUV', 'location': 'B', 'mileage': "7500", 'day': "75", 'mile': "0.31", 'status': 'unavailable'},
        {'make': 'BMW', 'model': '5 Series', 'type': 'Sedan', 'location': 'C', 'mileage': "8000", 'day': "80", 'mile': "0.32", 'status': 'available'},
        {'make': 'Mercedes-Benz', 'model': 'E-Class', 'type': 'Sedan', 'location': 'A', 'mileage': "8500", 'day': "85", 'mile': "0.33", 'status': 'unavailable'},
        {'make': 'Hyundai', 'model': 'Santa Fe', 'type': 'SUV', 'location': 'B', 'mileage': "9000", 'day': "90", 'mile': "0.34", 'status': 'available'},
        {'make': 'Audi', 'model': 'Q5', 'type': 'SUV', 'location': 'C', 'mileage': "9500", 'day': "95", 'mile': "0.35", 'status': 'unavailable'},
        {'make': 'Kia', 'model': 'Sorento', 'type': 'SUV', 'location': 'A', 'mileage': "10000", 'day': "100", 'mile': "0.36", 'status': 'available'},
        {'make': 'Mazda', 'model': 'CX-5', 'type': 'SUV', 'location': 'B', 'mileage': "10500", 'day': "105", 'mile': "0.37", 'status': 'unavailable'},
        {'make': 'Lexus', 'model': 'RX', 'type': 'SUV', 'location': 'C', 'mileage': "11000", 'day': "110", 'mile': "0.38", 'status': 'available'},
        {'make': 'Volkswagen', 'model': 'Tiguan', 'type': 'SUV', 'location': 'A', 'mileage': "11500", 'day': "115", 'mile': "0.39", 'status': 'unavailable'},
        {'make': 'Infiniti', 'model': 'QX60', 'type': 'SUV', 'location': 'B', 'mileage': "12000", 'day': "120", 'mile': "0.40", 'status': 'available'},
        {'make': 'Buick', 'model': 'Enclave', 'type': 'SUV', 'location': 'C', 'mileage': "12500", 'day': "125", 'mile': "0.41", 'status': 'unavailable'},
        {'make': 'Chrysler', 'model': 'Pacifica', 'type': 'Minivan', 'location': 'A', 'mileage': "13000", 'day': "130", 'mile': "0.42", 'status': 'available'},
        {'make': 'Volvo', 'model': 'XC60', 'type': 'SUV', 'location': 'B', 'mileage': "13500", 'day': "135", 'mile': "0.43", 'status': 'unavailable'},
        {'make': 'Cadillac', 'model': 'Escalade', 'type': 'SUV', 'location': 'C', 'mileage': "14000", 'day': "140", 'mile': "0.44", 'status': 'available'},
        {'make': 'Acura', 'model': 'MDX', 'type': 'SUV', 'location': 'A', 'mileage': "14500", 'day': "145", 'mile': "0.45", 'status': 'unavailable'},
        {'make': 'Lincoln', 'model': 'Navigator', 'type': 'SUV', 'location': 'B', 'mileage': "15000", 'day': "150", 'mile': "0.46", 'status': 'available'},
        {'make': 'Jeep', 'model': 'Grand Cherokee', 'type': 'SUV', 'location': 'C', 'mileage': "15500", 'day': "155", 'mile': "0.47", 'status': 'unavailable'},
        {'make': 'Land Rover', 'model': 'Range Rover', 'type': 'SUV', 'location': 'A', 'mileage': "16000", 'day': "160", 'mile': "0.48", 'status': 'available'},
        {'make': 'GMC', 'model': 'Yukon', 'type': 'SUV', 'location': 'B', 'mileage': "16500", 'day': "165", 'mile': "0.49", 'status': 'unavailable'},
        {'make': 'Subaru', 'model': 'Crosstrek', 'type': 'SUV', 'location': 'C', 'mileage': "17000", 'day': "170", 'mile': "0.50", 'status': 'available'},
        {'make': 'Mitsubishi', 'model': 'Outlander', 'type': 'SUV', 'location': 'A', 'mileage': "17500", 'day': "175", 'mile': "0.51", 'status': 'unavailable'},
        {'make': 'Ford', 'model': 'Escape', 'type': 'SUV', 'location': 'B', 'mileage': "18000", 'day': "180", 'mile': "0.52", 'status': 'available'},
        {'make': 'Toyota', 'model': 'Highlander', 'type': 'SUV', 'location': 'C', 'mileage': "18500", 'day': "185", 'mile': "0.53", 'status': 'unavailable'},
        {'make': 'Chevrolet', 'model': 'Equinox', 'type': 'SUV', 'location': 'A', 'mileage': "19000", 'day': "190", 'mile': "0.54", 'status': 'available'},
        {'make': 'Honda', 'model': 'Pilot', 'type': 'SUV', 'location': 'B', 'mileage': "19500", 'day': "195", 'mile': "0.55", 'status': 'unavailable'},
        {'make': 'Nissan', 'model': 'Pathfinder', 'type': 'SUV', 'location': 'C', 'mileage': "20000", 'day': "200", 'mile': "0.56", 'status': 'available'},
        {'make': 'Tesla', 'model': 'Model X', 'type': 'Electric', 'location': 'A', 'mileage': "20500", 'day': "205", 'mile': "0.57", 'status': 'unavailable'},
        {'make': 'BMW', 'model': 'X5', 'type': 'SUV', 'location': 'B', 'mileage': "21000", 'day': "210", 'mile': "0.58", 'status': 'available'},
        {'make': 'Mercedes-Benz', 'model': 'GLC', 'type': 'SUV', 'location': 'C', 'mileage': "21500", 'day': "215", 'mile': "0.59", 'status': 'unavailable'},
        {'make': 'Hyundai', 'model': 'Tucson', 'type': 'SUV', 'location': 'A', 'mileage': "22000", 'day': "220", 'mile': "0.60", 'status': 'available'},
        {'make': 'Audi', 'model': 'A6', 'type': 'Sedan', 'location': 'B', 'mileage': "22500", 'day': "225", 'mile': "0.61", 'status': 'unavailable'},
        {'make': 'Kia', 'model': 'Sportage', 'type': 'SUV', 'location': 'C', 'mileage': "23000", 'day': "230", 'mile': "0.62", 'status': 'available'},
        {'make': 'Mazda', 'model': 'CX-9', 'type': 'SUV', 'location': 'A', 'mileage': "23500", 'day': "235", 'mile': "0.63", 'status': 'unavailable'},
        {'make': 'Lexus', 'model': 'NX', 'type': 'SUV', 'location': 'B', 'mileage': "24000", 'day': "240", 'mile': "0.64", 'status': 'available'},
        {'make': 'Volkswagen', 'model': 'Atlas', 'type': 'SUV', 'location': 'C', 'mileage': "24500", 'day': "245", 'mile': "0.65", 'status': 'unavailable'},
        {'make': 'Infiniti', 'model': 'QX80', 'type': 'SUV', 'location': 'A', 'mileage': "25000", 'day': "250", 'mile': "0.66", 'status': 'available'},
        {'make': 'Buick', 'model': 'Encore', 'type': 'SUV', 'location': 'B', 'mileage': "25500", 'day': "255", 'mile': "0.67", 'status': 'unavailable'},
        {'make': 'Chrysler', 'model': 'Voyager', 'type': 'Minivan', 'location': 'C', 'mileage': "26000", 'day': "260", 'mile': "0.68", 'status': 'available'},
        {'make': 'Volvo', 'model': 'XC90', 'type': 'SUV', 'location': 'A', 'mileage': "26500", 'day': "265", 'mile': "0.69", 'status': 'unavailable'},
        {'make': 'Cadillac', 'model': 'XT5', 'type': 'SUV', 'location': 'B', 'mileage': "27000", 'day': "270", 'mile': "0.70", 'status': 'available'},
        {'make': 'Acura', 'model': 'RDX', 'type': 'SUV', 'location': 'C', 'mileage': "27500", 'day': "275", 'mile': "0.71", 'status': 'unavailable'},
        {'make': 'Lincoln', 'model': 'Corsair', 'type': 'SUV', 'location': 'A', 'mileage': "28000", 'day': "280", 'mile': "0.72", 'status': 'available'},
        {'make': 'Jeep', 'model': 'Cherokee', 'type': 'SUV', 'location': 'B', 'mileage': "28500", 'day': "285", 'mile': "0.73", 'status': 'unavailable'},
        {'make': 'Land Rover', 'model': 'Discovery', 'type': 'SUV', 'location': 'C', 'mileage': "29000", 'day': "290", 'mile': "0.74", 'status': 'available'},
        {'make': 'GMC', 'model': 'Terrain', 'type': 'SUV', 'location': 'A', 'mileage': "29500", 'day': "295", 'mile': "0.75", 'status': 'unavailable'},
        {'make': 'Subaru', 'model': 'Legacy', 'type': 'Sedan', 'location': 'B', 'mileage': "30000", 'day': "300", 'mile': "0.76", 'status': 'available'},
        {'make': 'Mitsubishi', 'model': 'Eclipse Cross', 'type': 'SUV', 'location': 'C', 'mileage': "30500", 'day': "305", 'mile': "0.77", 'status': 'unavailable'},
        {'make': 'Ford', 'model': 'Edge', 'type': 'SUV', 'location': 'A', 'mileage': "31000", 'day': "310", 'mile': "0.78", 'status': 'available'},
        {'make': 'Toyota', 'model': 'Sienna', 'type': 'Minivan', 'location': 'B', 'mileage': "31500", 'day': "315", 'mile': "0.79", 'status': 'unavailable'},
        {'make': 'Chevrolet', 'model': 'Traverse', 'type': 'SUV', 'location': 'C', 'mileage': "32000", 'day': "320", 'mile': "0.80", 'status': 'available'},
        {'make': 'Honda', 'model': 'Odyssey', 'type': 'Minivan', 'location': 'A', 'mileage': "32500", 'day': "325", 'mile': "0.81", 'status': 'unavailable'},
        {'make': 'Nissan', 'model': 'Murano', 'type': 'SUV', 'location': 'B', 'mileage': "33000", 'day': "330", 'mile': "0.82", 'status': 'available'},
        {'make': 'Tesla', 'model': 'Model Y', 'type': 'Electric', 'location': 'C', 'mileage': "33500", 'day': "335", 'mile': "0.83", 'status': 'unavailable'},
        {'make': 'BMW', 'model': 'X3', 'type': 'SUV', 'location': 'A', 'mileage': "34000", 'day': "340", 'mile': "0.84", 'status': 'available'},
        {'make': 'Mercedes-Benz', 'model': 'GLE', 'type': 'SUV', 'location': 'B', 'mileage': "34500", 'day': "345", 'mile': "0.85", 'status': 'unavailable'},
        {'make': 'Hyundai', 'model': 'Kona', 'type': 'SUV', 'location': 'C', 'mileage': "35000", 'day': "350", 'mile': "0.86", 'status': 'available'},
        {'make': 'Audi', 'model': 'Q7', 'type': 'SUV', 'location': 'A', 'mileage': "35500", 'day': "355", 'mile': "0.87", 'status': 'unavailable'},
        {'make': 'Kia', 'model': 'Niro', 'type': 'SUV', 'location': 'B', 'mileage': "36000", 'day': "360", 'mile': "0.88", 'status': 'available'},
        {'make': 'Mazda', 'model': 'MX-5 Miata', 'type': 'Convertible', 'location': 'C', 'mileage': "36500", 'day': "365", 'mile': "0.89", 'status': 'unavailable'},
        {'make': 'Lexus', 'model': 'LC', 'type': 'Coupe', 'location': 'A', 'mileage': "37000", 'day': "370", 'mile': "0.90", 'status': 'available'},
        {'make': 'Volkswagen', 'model': 'Passat', 'type': 'Sedan', 'location': 'B', 'mileage': "37500", 'day': "375", 'mile': "0.91", 'status': 'unavailable'},
        {'make': 'Infiniti', 'model': 'Q60', 'type': 'Coupe', 'location': 'C', 'mileage': "38000", 'day': "380", 'mile': "0.92", 'status': 'available'},
        {'make': 'Buick', 'model': 'LaCrosse', 'type': 'Sedan', 'location': 'A', 'mileage': "38500", 'day': "385", 'mile': "0.93", 'status': 'unavailable'},
        {'make': 'Chrysler', 'model': '300', 'type': 'Sedan', 'location': 'B', 'mileage': "39000", 'day': "390", 'mile': "0.94", 'status': 'available'},
        {'make': 'Volvo', 'model': 'V90', 'type': 'Wagon', 'location': 'C', 'mileage': "39500", 'day': "395", 'mile': "0.95", 'status': 'unavailable'},
        {'make': 'Cadillac', 'model': 'XT4', 'type': 'SUV', 'location': 'A', 'mileage': "40000", 'day': "400", 'mile': "0.96", 'status': 'available'},
        {'make': 'Acura', 'model': 'ILX', 'type': 'Sedan', 'location': 'B', 'mileage': "40500", 'day': "405", 'mile': "0.97", 'status': 'unavailable'},
        {'make': 'Lincoln', 'model': 'Nautilus', 'type': 'SUV', 'location': 'C', 'mileage': "41000", 'day': "410", 'mile': "0.98", 'status': 'available'},
        {'make': 'Jeep', 'model': 'Renegade', 'type': 'SUV', 'location': 'A', 'mileage': "41500", 'day': "415", 'mile': "0.99", 'status': 'unavailable'},
        {'make': 'Land Rover', 'model': 'Evoque', 'type': 'SUV', 'location': 'B', 'mileage': "42000", 'day': "420", 'mile': "1.00", 'status': 'available'}
    ]


    for car in cars:
        build_instance( Car, car )

    db.session.commit()

    print("Testing data for cars has been added to the database.")