/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nFiy596RdJJ
 */
import Link from "next/link"
import { LinkBar } from "../common-elements/link-bar"

export function AboutPage() {
  return (
    (<div key="1" className="flex flex-col min-h-[100dvh]">
      <LinkBar/>
      <main className="flex-1">
        <div className="container px-4 md:px-6 py-8">
          <h1 className="text-3xl font-bold">About Gatoride</h1>
          <p className="text-gray-500 dark:text-gray-400 mt-4">
            Gatoride is a leading company in the automotive industry, specializing in innovative solutions for car
            enthusiasts. Our mission is to provide top-notch services and products that exceed customer expectations.
          </p>
          <p className="text-gray-500 dark:text-gray-400 mt-4">
            At Gatoride, we are committed to excellence, quality, and customer satisfaction. With a team of dedicated
            professionals, we strive to deliver exceptional experiences to our clients.
          </p>
        </div>
      </main>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Gatoride. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>)
  );
}
