/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cKAhSxY4EhB
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CardContent, CardFooter, Card, CardTitle, CardDescription, CardHeader } from "@/components/ui/card"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"
import { Label } from "@/components/ui/label"

import { LinkBar } from "../common-elements/link-bar";
import { DateSelector } from "../input-elements/date-selector"

export function HomePage() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <LinkBar/>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div
            className="container flex flex-col items-center justify-center space-y-4 text-center px-4 md:px-6">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Rent the perfect car</h1>
              <p
                className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Experience the freedom of the open road with our top-quality rental cars.
              </p>
            </div>
            <DateSelector/>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div
            className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Why choose Gatoride?</h2>
              <p
                className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                We're committed to providing the best car rental experience with our exceptional service and affordable
                rates.
              </p>
            </div>
            <div
              className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <img
                alt="Image"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                height="310"
                src="/placeholder.svg"
                width="550" />
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Comfort</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Enjoy a smooth and comfortable ride in our well-maintained vehicles.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Style</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Arrive in style with our selection of sleek and elegant cars.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Convenience</h3>
                      <p className="text-gray-500 dark:text-gray-400">
                        Experience the freedom of the open road with our top-quality rental cars.
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div
            className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Explore our Fleet</h2>
              <p
                className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Choose the perfect vehicle for your journey from our wide range of cars.
              </p>
            </div>
            <div
              className="mx-auto grid max-w-5xl items-center gap-4 lg:grid-cols-3 lg:gap-6">
              <Card className="w-full max-w-sm">
                <CardContent className="flex flex-col items-center gap-4">
                  <img
                    alt="Car"
                    className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                    height="225"
                    src="/placeholder.svg"
                    width="400" />
                  <div className="space-y-2 text-center">
                    <h3 className="text-xl font-bold">Economy</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Compact and fuel-efficient</p>
                  </div>
                </CardContent>
                <CardFooter className="flex justify-center">
                  <Link
                    className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white px-4 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                    href="#">
                    View Details
                  </Link>
                </CardFooter>
              </Card>
              <Card className="w-full max-w-sm">
                <CardContent className="flex flex-col items-center gap-4">
                  <img
                    alt="Car"
                    className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                    height="225"
                    src="/placeholder.svg"
                    width="400" />
                  <div className="space-y-2 text-center">
                    <h3 className="text-xl font-bold">Standard</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Comfortable and reliable</p>
                  </div>
                </CardContent>
                <CardFooter className="flex justify-center">
                  <Link
                    className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white px-4 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                    href="#">
                    View Details
                  </Link>
                </CardFooter>
              </Card>
              <Card className="w-full max-w-sm">
                <CardContent className="flex flex-col items-center gap-4">
                  <img
                    alt="Car"
                    className="aspect-video overflow-hidden rounded-xl object-cover object-center"
                    height="225"
                    src="/placeholder.svg"
                    width="400" />
                  <div className="space-y-2 text-center">
                    <h3 className="text-xl font-bold">SUV</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Spacious and versatile</p>
                  </div>
                </CardContent>
                <CardFooter className="flex justify-center">
                  <Link
                    className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white px-4 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                    href="#">
                    View Details
                  </Link>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
        <div className="fixed bottom-4 right-4 z-50">
          <Popover>
            <PopoverTrigger asChild>
              <Button className="rounded-full" size="icon" variant="outline">
                <UserIcon className="w-6 h-6" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="p-0">
              <Card className="shadow-none border-0">
                <CardHeader className="border-b">
                  <CardTitle>Login</CardTitle>
                  <CardDescription>Enter your credentials to log in.</CardDescription>
                </CardHeader>
                <CardContent className="p-6">
                  <div className="space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="username">Username</Label>
                      <Input id="username" required type="text" />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="password">Password</Label>
                      <Input id="password" required type="password" />
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <Button className="w-full">Login</Button>
                </CardFooter>
              </Card>
            </PopoverContent>
          </Popover>
        </div>
      </main>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}


function UserIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>)
  );
}
