import { Providers } from "./providers"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en" className="dark text-foreground bg-background">
      <body>
        <Providers>
            {children}
        </Providers>
      </body>
    </html>
  )
}
